import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,readdirSync} from 'node:fs';
import {join} from 'node:path';
import {root} from './local-runtime.mjs';
import {validateSnapshot,assertSafeEnvironment,assertFreshProject,hash} from './bootstrap-manifest.mjs';
import {checkFutureOrder} from './check-future-migrations.mjs';
import {canonical,structuralDiff} from './compare-schema-metadata.mjs';
const bytes=readFileSync(join(root,'supabase/bootstrap/legacy-manifest.json'));
const original=new Map(readdirSync(join(root,'supabase/migrations')).filter(f=>f.endsWith('.sql')).map(f=>[f,readFileSync(join(root,'supabase/migrations',f))]));
test('approved 268 migrations and sanitized exception validate before any DB creation',()=>{const r=validateSnapshot(bytes,original);assert.equal(r.entries.length,268);assert.equal(r.manifest.exceptions['20260427190000'].kind,'authorized-sanitized-scheduler');});
test('modified legacy SQL fails',()=>{const m=new Map(original);m.set(m.keys().next().value,Buffer.from('select 1;'));assert.throws(()=>validateSnapshot(bytes,m),/hash mismatch/);});
test('missing migration fails',()=>{const m=new Map(original);m.delete(m.keys().next().value);assert.throws(()=>validateSnapshot(bytes,m),/Missing/);});
test('unregistered future file fails',()=>{const m=new Map(original);m.set('20261001000000_new.sql',Buffer.from('select 1;'));assert.throws(()=>validateSnapshot(bytes,m),/unregistered/);});
test('modified manifest, dependency or duplicate exception cannot bypass approval seal',()=>{const m=JSON.parse(bytes);m.entries.push(m.entries[0]);assert.throws(()=>validateSnapshot(Buffer.from(JSON.stringify(m)),original),/Unapproved/);});
test('target arguments and existing containers, volumes or networks are forbidden',()=>{for(const args of [['--linked'],['--db-url','remote'],['--local'],['existing-container']])assert.throws(()=>assertSafeEnvironment({},args),/target arguments/);for(const resource of ['supabase_db_phase0b-00000000','supabase_network_phase0b-00000000','phase0b-00000000-isolated'])assert.throws(()=>assertFreshProject('phase0b-00000000',[resource]),/existing resource/);assert.doesNotThrow(()=>assertFreshProject('phase0b-00000000',['another-project']));});
test('remote and ambiguous environment overrides are forbidden',()=>{for(const key of ['DOCKER_HOST','DOCKER_CONTEXT','SUPABASE_PROJECT_ID','SUPABASE_ACCESS_TOKEN','PGHOST','PGSERVICE','PGOPTIONS','DATABASE_URL','DB_URL','NEXT_PUBLIC_SUPABASE_URL'])assert.throws(()=>assertSafeEnvironment({[key]:'untrusted'},[]),/Ambiguous/);});
test('ordinary process environment is accepted',()=>assert.doesNotThrow(()=>assertSafeEnvironment({PATH:'runtime',TEMP:'temporary'},[])));
test('future relation forward dependency fails',()=>{const v=checkFutureOrder(new Map([['20261001000000_consumer.sql','alter table public.later add column n int;'],['20261002000000_provider.sql','create table public.later(id int);']]));assert.equal(v[0].kind,'future-object');});
test('unqualified consumer of future relation fails',()=>assert.equal(checkFutureOrder(new Map([['20261001000000_a.sql','select * from later;'],['20261002000000_b.sql','create table public.later(id int);']]))[0].kind,'future-object'));
test('unresolved unqualified future declaration fails closed',()=>assert.equal(checkFutureOrder(new Map([['20261001000000_a.sql','create table later(id int);']]))[0].kind,'unresolved-object-declaration-requires-review'));
test('future function forward dependency fails even in body',()=>assert.equal(checkFutureOrder(new Map([['20261001000000_a.sql','create function public.a() returns int language sql as $$ select public.b() $$;'],['20261002000000_b.sql','create function public.b() returns int language sql as $$ select 1 $$;']]))[0].kind,'future-object'));
test('future column forward dependency fails',()=>assert.equal(checkFutureOrder(new Map([['20261001000000_a.sql','update public.t set added=1;'],['20261002000000_b.sql','alter table public.t add column added integer;']]))[0].kind,'future-column'));
test('unresolved future dynamic SQL fails closed',()=>assert.equal(checkFutureOrder(new Map([['20261001000000_a.sql','do $$ begin execute arbitrary_ddl; end $$;']]))[0].kind,'dynamic-SQL-requires-review'));
test('registered chronological incremental passes, preserving frozen legacy',()=>{const m=new Map(original);const file='20261001000000_future.sql',source=Buffer.from('create table if not exists public.phase0_synthetic_future(id integer);');m.set(file,source);const r=validateSnapshot(bytes,m,{legacyCutoff:'20260915190657',entries:[{version:'20261001000000',file,sha256:hash(source)}]});assert.equal(r.entries.length,269);});
test('incremental registration cannot insert another legacy exception',()=>assert.throws(()=>validateSnapshot(bytes,original,{legacyCutoff:'20260915190657',entries:[{version:'20260401102000'}]}),/chronological/));
test('reviewed legacy dependencies preserve providers, consumers and replacements',()=>{
  const {entries}=validateSnapshot(bytes,original);const index=v=>entries.findIndex(e=>e.version===v);
  for(const [provider,consumer] of [['20260427180000','20260427190000'],['20260427190000','20260629190000'],['20260426007000','20260330193500'],['20260426140000','20260424222000'],['20260426004000','20260424224500'],['20260426000000','20260323183000']])assert.ok(index(provider)<index(consumer));
  for(const version of ['20260426007000','20260426140000','20260426004000','20260426000000'])assert.equal(entries[index(version)].requiredEmptyRelations.length,2);
});
test('structural changes remain individually unresolved',()=>{const a={relations:[{schema:'public',name:'synthetic',rls:false}]},b={relations:[{schema:'public',name:'synthetic',rls:true}]};const diff=structuralDiff(a,b);assert.equal(diff.length,1);assert.equal(diff[0].status,'unresolved');assert.equal(diff[0].justification,null);});
test('fingerprint canonicalization preserves physical column order',()=>{const a={columns:[{name:'a'},{name:'b'}]},b={columns:[{name:'b'},{name:'a'}]};assert.notDeepEqual(canonical(a),canonical(b));assert.deepEqual(canonical({z:1,a:2}),canonical({a:2,z:1}));});
