-- Identical metadata query for local and remote; no application rows or SQL bodies returned.
BEGIN READ ONLY;
SET LOCAL statement_timeout='8s';
SET LOCAL lock_timeout='1s';
SET LOCAL search_path=public,extensions;
WITH namespaces AS (SELECT oid,nspname FROM pg_namespace WHERE nspname IN ('public','private'))
SELECT jsonb_build_object(
 'relations',(SELECT coalesce(jsonb_agg(jsonb_build_object(
   'schema',n.nspname,'name',c.relname,'kind',c.relkind,'owner',pg_get_userbyid(c.relowner),'rls',c.relrowsecurity,'force_rls',c.relforcerowsecurity,
   'view_md5',CASE WHEN c.relkind IN ('v','m') THEN md5(pg_get_viewdef(c.oid)) END,'options',c.reloptions,
   'columns',(SELECT jsonb_agg(jsonb_build_object('name',a.attname,'type',format_type(a.atttypid,a.atttypmod),'not_null',a.attnotnull,'identity',a.attidentity,'generated',a.attgenerated,'default_md5',md5(pg_get_expr(d.adbin,d.adrelid))) ORDER BY a.attnum) FROM pg_attribute a LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum WHERE a.attrelid=c.oid AND a.attnum>0 AND NOT a.attisdropped)
 ) ORDER BY n.nspname,c.relname),'[]') FROM pg_class c JOIN namespaces n ON n.oid=c.relnamespace WHERE c.relkind IN ('r','p','v','m','S')),
 'constraints',(SELECT coalesce(jsonb_agg(jsonb_build_object('schema',n.nspname,'table',c.relname,'name',k.conname,'type',k.contype,'validated',k.convalidated,'definition_md5',md5(pg_get_constraintdef(k.oid))) ORDER BY n.nspname,c.relname,k.conname),'[]') FROM pg_constraint k JOIN pg_class c ON c.oid=k.conrelid JOIN namespaces n ON n.oid=c.relnamespace),
 'indexes',(SELECT coalesce(jsonb_agg(jsonb_build_object('schema',n.nspname,'table',c.relname,'name',ic.relname,'unique',i.indisunique,'valid',i.indisvalid,'definition_md5',md5(pg_get_indexdef(i.indexrelid))) ORDER BY n.nspname,c.relname,ic.relname),'[]') FROM pg_index i JOIN pg_class c ON c.oid=i.indrelid JOIN pg_class ic ON ic.oid=i.indexrelid JOIN namespaces n ON n.oid=c.relnamespace),
 'functions',(SELECT coalesce(jsonb_agg(jsonb_build_object('schema',n.nspname,'name',p.proname,'arguments',pg_get_function_identity_arguments(p.oid),'result',pg_get_function_result(p.oid),'owner',pg_get_userbyid(p.proowner),'language',l.lanname,'security_definer',p.prosecdef,'volatility',p.provolatile,'strict',p.proisstrict,'parallel',p.proparallel,'settings',p.proconfig,'definition_md5',md5(replace(pg_get_functiondef(p.oid),E'\r','')),'body_md5',md5(replace(p.prosrc,E'\r',''))) ORDER BY n.nspname,p.proname,pg_get_function_identity_arguments(p.oid)),'[]') FROM pg_proc p JOIN namespaces n ON n.oid=p.pronamespace JOIN pg_language l ON l.oid=p.prolang WHERE p.prokind IN ('f','p')),
 'triggers',(SELECT coalesce(jsonb_agg(jsonb_build_object('schema',n.nspname,'table',c.relname,'name',t.tgname,'function_schema',fn.nspname,'function',p.proname,'enabled',t.tgenabled,'definition_md5',md5(pg_get_triggerdef(t.oid))) ORDER BY n.nspname,c.relname,t.tgname),'[]') FROM pg_trigger t JOIN pg_class c ON c.oid=t.tgrelid JOIN namespaces n ON n.oid=c.relnamespace JOIN pg_proc p ON p.oid=t.tgfoid JOIN pg_namespace fn ON fn.oid=p.pronamespace WHERE NOT t.tgisinternal),
 'policies',(SELECT coalesce(jsonb_agg(jsonb_build_object('schema',schemaname,'table',tablename,'name',policyname,'command',cmd,'roles',roles,'permissive',permissive,'using_md5',md5(qual),'check_md5',md5(with_check)) ORDER BY schemaname,tablename,policyname),'[]') FROM pg_policies WHERE schemaname IN ('public','private')),
 'grants',(SELECT coalesce(jsonb_agg(x ORDER BY x::text),'[]') FROM (
   SELECT jsonb_build_object('kind','relation','schema',n.nspname,'name',c.relname,'grantee',CASE WHEN a.grantee=0 THEN 'PUBLIC' ELSE pg_get_userbyid(a.grantee) END,'grantor',pg_get_userbyid(a.grantor),'privilege',a.privilege_type,'grantable',a.is_grantable) AS x FROM pg_class c JOIN namespaces n ON n.oid=c.relnamespace CROSS JOIN LATERAL aclexplode(coalesce(c.relacl,acldefault(CASE WHEN c.relkind='S' THEN 'S'::"char" ELSE 'r'::"char" END,c.relowner))) a WHERE c.relkind IN ('r','p','v','m','S')
   UNION ALL SELECT jsonb_build_object('kind','function','schema',n.nspname,'name',p.proname,'arguments',pg_get_function_identity_arguments(p.oid),'grantee',CASE WHEN a.grantee=0 THEN 'PUBLIC' ELSE pg_get_userbyid(a.grantee) END,'grantor',pg_get_userbyid(a.grantor),'privilege',a.privilege_type,'grantable',a.is_grantable) FROM pg_proc p JOIN namespaces n ON n.oid=p.pronamespace CROSS JOIN LATERAL aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) a
   UNION ALL SELECT jsonb_build_object('kind','schema','schema',n.nspname,'grantee',CASE WHEN a.grantee=0 THEN 'PUBLIC' ELSE pg_get_userbyid(a.grantee) END,'grantor',pg_get_userbyid(a.grantor),'privilege',a.privilege_type,'grantable',a.is_grantable) FROM pg_namespace n CROSS JOIN LATERAL aclexplode(coalesce(n.nspacl,acldefault('n',n.nspowner))) a WHERE n.nspname IN ('public','private')
 ) q),
 'default_grants',(SELECT coalesce(jsonb_agg(jsonb_build_object('schema',coalesce(n.nspname,'*'),'owner',pg_get_userbyid(d.defaclrole),'kind',d.defaclobjtype,'grantee',CASE WHEN a.grantee=0 THEN 'PUBLIC' ELSE pg_get_userbyid(a.grantee) END,'privilege',a.privilege_type,'grantable',a.is_grantable) ORDER BY coalesce(n.nspname,'*'),d.defaclobjtype,pg_get_userbyid(d.defaclrole),a.grantee,a.privilege_type),'[]') FROM pg_default_acl d LEFT JOIN pg_namespace n ON n.oid=d.defaclnamespace CROSS JOIN LATERAL aclexplode(d.defaclacl) a WHERE n.nspname IN ('public','private') OR n.nspname IS NULL),
 'extensions',(SELECT jsonb_agg(jsonb_build_object('name',e.extname,'version',e.extversion,'schema',n.nspname) ORDER BY e.extname) FROM pg_extension e JOIN pg_namespace n ON n.oid=e.extnamespace),
 'event_triggers',(SELECT coalesce(jsonb_agg(jsonb_build_object('name',e.evtname,'event',e.evtevent,'enabled',e.evtenabled,'tags',e.evttags,'function_schema',n.nspname,'function',p.proname) ORDER BY e.evtname),'[]') FROM pg_event_trigger e JOIN pg_proc p ON p.oid=e.evtfoid JOIN pg_namespace n ON n.oid=p.pronamespace),
 'cron',(SELECT coalesce(jsonb_agg(jsonb_build_object('name',jobname,'schedule',schedule,'active',active,'database',database,'username',username,'command_md5',md5(command),'command_kind',CASE WHEN command ~* '^\s*select\s+(public[.])?[a-z_]+\s*\(\s*\)\s*;?\s*$' THEN 'function-call-no-arguments' ELSE 'other-command-hashed' END) ORDER BY jobname),'[]') FROM cron.job),
 'queue_relations',(SELECT coalesce(jsonb_agg(jsonb_build_object('schema',n.nspname,'name',c.relname,'kind',c.relkind) ORDER BY n.nspname,c.relname),'[]') FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname IN ('net','pgmq') AND c.relkind IN ('r','p','v','m'))
) AS metadata;
ROLLBACK;
