BEGIN READ ONLY;
SET LOCAL statement_timeout='8s'; SET LOCAL lock_timeout='1s'; SET LOCAL search_path=public,extensions;
SELECT jsonb_build_object(
 'postgres',version(), 'server_version',current_setting('server_version'),
 'installed',(SELECT jsonb_build_object('version',e.extversion,'schema',n.nspname,'owner',pg_get_userbyid(e.extowner)) FROM pg_extension e JOIN pg_namespace n ON n.oid=e.extnamespace WHERE e.extname='pg_net'),
 'available',(SELECT jsonb_agg(to_jsonb(v) ORDER BY version) FROM pg_available_extension_versions v WHERE name='pg_net'),
 'functions',(SELECT jsonb_agg(jsonb_build_object('name',p.proname,'arguments',pg_get_function_identity_arguments(p.oid),'definition',pg_get_functiondef(p.oid),'body_md5',md5(p.prosrc),'owner',pg_get_userbyid(p.proowner),'security_definer',p.prosecdef,'settings',p.proconfig,'acl',p.proacl::text,'extension',e.extname) ORDER BY p.proname) FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace LEFT JOIN pg_depend d ON d.classid='pg_proc'::regclass AND d.objid=p.oid AND d.deptype='e' LEFT JOIN pg_extension e ON e.oid=d.refobjid WHERE n.nspname='net' AND p.proname IN ('http_get','http_post')),
 'provider_hooks',(SELECT jsonb_agg(jsonb_build_object('name',p.proname,'definition',pg_get_functiondef(p.oid),'owner',pg_get_userbyid(p.proowner),'acl',p.proacl::text) ORDER BY p.proname) FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='extensions' AND p.proname='grant_pg_net_access'),
 'event_triggers',(SELECT jsonb_agg(jsonb_build_object('name',e.evtname,'enabled',e.evtenabled,'tags',e.evttags,'owner',pg_get_userbyid(e.evtowner),'function',e.evtfoid::regproc::text) ORDER BY e.evtname) FROM pg_event_trigger e WHERE e.evtfoid IN (SELECT oid FROM pg_proc WHERE proname='grant_pg_net_access')),
 'relations',(SELECT jsonb_agg(jsonb_build_object('name',c.relname,'kind',c.relkind,'owner',pg_get_userbyid(c.relowner),'acl',c.relacl::text,'rls',c.relrowsecurity,'force_rls',c.relforcerowsecurity) ORDER BY c.relname) FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='net' AND c.relkind IN ('r','S')),
 'roles',(SELECT jsonb_agg(jsonb_build_object('name',r.rolname,'superuser',r.rolsuper,'bypassrls',r.rolbypassrls,'inherit',r.rolinherit,'schema_usage',has_schema_privilege(r.oid,'net','USAGE'),'schema_create',has_schema_privilege(r.oid,'net','CREATE'),
 'execute',(SELECT jsonb_agg(jsonb_build_object('name',p.proname,'allowed',has_function_privilege(r.oid,p.oid,'EXECUTE')) ORDER BY p.proname) FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='net' AND p.proname IN ('http_get','http_post')),
 'relations',(SELECT jsonb_agg(jsonb_build_object('name',c.relname,'privileges',(SELECT jsonb_object_agg(priv,CASE WHEN c.relkind='S' THEN has_sequence_privilege(r.oid,c.oid,priv) ELSE has_table_privilege(r.oid,c.oid,priv) END) FROM unnest(CASE WHEN c.relkind='S' THEN ARRAY['USAGE','SELECT','UPDATE'] ELSE ARRAY['SELECT','INSERT','UPDATE','DELETE','TRUNCATE','REFERENCES','TRIGGER','MAINTAIN'] END) priv)) ORDER BY c.relname) FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='net' AND c.relkind IN ('r','S'))) ORDER BY r.rolname) FROM pg_roles r WHERE r.rolname IN ('anon','authenticated','authenticator','service_role','postgres'))
) AS metadata;
ROLLBACK;
