BEGIN READ ONLY; SET LOCAL statement_timeout='8s'; SET LOCAL lock_timeout='1s';
SELECT jsonb_build_object(
 'function', (SELECT jsonb_build_object('definition',pg_get_functiondef(p.oid),'body',p.prosrc,'owner',pg_get_userbyid(p.proowner),'security_definer',p.prosecdef,'settings',p.proconfig,'acl',p.proacl::text,'body_md5',md5(replace(p.prosrc,E'\r',''))) FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='rls_auto_enable'),
 'event_trigger',(SELECT jsonb_build_object('name',e.evtname,'owner',pg_get_userbyid(e.evtowner),'event',e.evtevent,'enabled',e.evtenabled,'tags',e.evttags,'function',e.evtfoid::regprocedure::text) FROM pg_event_trigger e WHERE e.evtname='ensure_rls'),
 'tables',(SELECT jsonb_agg(jsonb_build_object('name',c.relname,'owner',pg_get_userbyid(c.relowner),'rls',c.relrowsecurity,'force_rls',c.relforcerowsecurity,'acl',c.relacl::text) ORDER BY c.relname) FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relname IN ('ar_name_inferred_sex','ar_phone_area_codes','cron_config','tracking_queue')),
 'policies',(SELECT coalesce(jsonb_agg(to_jsonb(p) ORDER BY tablename,policyname),'[]') FROM pg_policies p WHERE schemaname='public' AND tablename IN ('ar_name_inferred_sex','ar_phone_area_codes','cron_config','tracking_queue')),
 'roles',(SELECT jsonb_agg(jsonb_build_object('name',rolname,'superuser',rolsuper,'bypassrls',rolbypassrls,'inherit',rolinherit) ORDER BY rolname) FROM pg_roles WHERE rolname IN ('anon','authenticated','service_role')),
 'effective_privileges',(SELECT jsonb_agg(jsonb_build_object('role',r.role,'table',t.name,'schema_usage',has_schema_privilege(r.role,'public','USAGE'),'select',has_table_privilege(r.role,'public.'||t.name,'SELECT'),'insert',has_table_privilege(r.role,'public.'||t.name,'INSERT'),'update',has_table_privilege(r.role,'public.'||t.name,'UPDATE'),'delete',has_table_privilege(r.role,'public.'||t.name,'DELETE'),'truncate',has_table_privilege(r.role,'public.'||t.name,'TRUNCATE')) ORDER BY r.role,t.name) FROM (VALUES('anon'),('authenticated'),('service_role'))r(role) CROSS JOIN (VALUES('ar_name_inferred_sex'),('ar_phone_area_codes'),('cron_config'),('tracking_queue'))t(name))
) AS metadata;
ROLLBACK;
