create table if not exists public.chatrace_gerencias (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  gerencia_id bigint not null references public.gerencias(id) on delete cascade,
  weight integer not null default 1 check (weight >= 0),
  phone_mode text not null default 'random' check (phone_mode in ('random', 'fair')),
  phone_kind text not null default 'carga' check (phone_kind in ('carga', 'ads', 'mkt')),
  interval_start_hour integer null check (interval_start_hour between 0 and 23),
  interval_end_hour integer null check (interval_end_hour between 0 and 23),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint chatrace_gerencias_user_gerencia_unique unique (user_id, gerencia_id)
);

alter table public.chatrace_gerencias enable row level security;

drop policy if exists "Users can read own chatrace_gerencias" on public.chatrace_gerencias;
create policy "Users can read own chatrace_gerencias"
  on public.chatrace_gerencias for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert own chatrace_gerencias" on public.chatrace_gerencias;
create policy "Users can insert own chatrace_gerencias"
  on public.chatrace_gerencias for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update own chatrace_gerencias" on public.chatrace_gerencias;
create policy "Users can update own chatrace_gerencias"
  on public.chatrace_gerencias for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete own chatrace_gerencias" on public.chatrace_gerencias;
create policy "Users can delete own chatrace_gerencias"
  on public.chatrace_gerencias for delete
  using (auth.uid() = user_id);

drop policy if exists "Admins can read all chatrace_gerencias" on public.chatrace_gerencias;
create policy "Admins can read all chatrace_gerencias"
  on public.chatrace_gerencias for select
  using (
    exists (
      select 1
      from public.profiles p
      where p.id = auth.uid() and p.role = 'admin'
    )
  );

drop policy if exists "Admins can insert all chatrace_gerencias" on public.chatrace_gerencias;
create policy "Admins can insert all chatrace_gerencias"
  on public.chatrace_gerencias for insert
  with check (
    exists (
      select 1
      from public.profiles p
      where p.id = auth.uid() and p.role = 'admin'
    )
  );

drop policy if exists "Admins can update all chatrace_gerencias" on public.chatrace_gerencias;
create policy "Admins can update all chatrace_gerencias"
  on public.chatrace_gerencias for update
  using (
    exists (
      select 1
      from public.profiles p
      where p.id = auth.uid() and p.role = 'admin'
    )
  )
  with check (
    exists (
      select 1
      from public.profiles p
      where p.id = auth.uid() and p.role = 'admin'
    )
  );

drop policy if exists "Admins can delete all chatrace_gerencias" on public.chatrace_gerencias;
create policy "Admins can delete all chatrace_gerencias"
  on public.chatrace_gerencias for delete
  using (
    exists (
      select 1
      from public.profiles p
      where p.id = auth.uid() and p.role = 'admin'
    )
  );
