-- Demand-based availability for landing phone assignment.
-- Measures whether each candidate gerencia had acquisition phones when real traffic requested a phone.

set statement_timeout = '10min';

create table if not exists public.landing_phone_availability_demands (
  id bigint generated by default as identity primary key,
  request_id uuid not null,
  user_id uuid not null references public.profiles(id) on delete cascade,
  landing_id uuid not null references public.landings(id) on delete cascade,
  landing_name text not null,
  gerencia_id integer not null references public.gerencias(id) on delete cascade,
  gerencia_external_id integer,
  gerencia_label text not null,
  phone_kind text not null,
  had_active_phone boolean not null,
  active_phone_count integer not null default 0,
  total_phone_count integer not null default 0,
  was_selected boolean not null default false,
  selected_phone_id bigint references public.gerencia_phones(id) on delete set null,
  selected_phone text,
  result_status text not null default 'ok',
  source text not null default 'landing-phone',
  checked_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create unique index if not exists landing_phone_availability_demands_request_gerencia_idx
  on public.landing_phone_availability_demands (request_id, gerencia_id);

create index if not exists landing_phone_availability_demands_user_checked_idx
  on public.landing_phone_availability_demands (user_id, checked_at desc);

create index if not exists landing_phone_availability_demands_landing_checked_idx
  on public.landing_phone_availability_demands (landing_id, checked_at desc);

create index if not exists landing_phone_availability_demands_gerencia_checked_idx
  on public.landing_phone_availability_demands (gerencia_id, checked_at desc);

alter table public.landing_phone_availability_demands enable row level security;

drop policy if exists "Users read own landing phone availability demands"
  on public.landing_phone_availability_demands;
create policy "Users read own landing phone availability demands"
  on public.landing_phone_availability_demands
  for select
  using (auth.uid() = user_id);

drop policy if exists "Admins read all landing phone availability demands"
  on public.landing_phone_availability_demands;
create policy "Admins read all landing phone availability demands"
  on public.landing_phone_availability_demands
  for select
  using (
    exists (
      select 1
      from public.profiles p
      where p.id = auth.uid()
        and p.role = 'admin'
    )
  );

comment on table public.landing_phone_availability_demands is
  'Demand-based availability snapshots captured when landing-phone is requested by real traffic.';

create or replace function public.record_landing_phone_availability_demand(
  p_landing_name text,
  p_request_id uuid,
  p_source text default 'landing-phone',
  p_result_status text default 'ok',
  p_selected_gerencia_id integer default null,
  p_selected_phone_id bigint default null,
  p_selected_phone text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_current_hour integer := extract(hour from now())::integer;
  v_inserted integer := 0;
begin
  if nullif(trim(coalesce(p_landing_name, '')), '') is null then
    return jsonb_build_object('ok', false, 'reason', 'missing_landing_name');
  end if;

  if p_request_id is null then
    return jsonb_build_object('ok', false, 'reason', 'missing_request_id');
  end if;

  with landing_row as (
    select l.id, l.user_id, l.name
    from public.landings l
    where l.name = trim(p_landing_name)
    limit 1
  ),
  candidates as (
    select
      lr.id as landing_id,
      lr.user_id,
      lr.name as landing_name,
      lg.gerencia_id,
      lg.phone_kind,
      g.gerencia_id as gerencia_external_id,
      format(
        '%s (ID %s)',
        coalesce(nullif(trim(g.nombre), ''), format('Gerencia %s', coalesce(g.gerencia_id, g.id))),
        coalesce(g.gerencia_id, g.id)
      ) as gerencia_label
    from landing_row lr
    join public.landings_gerencias lg on lg.landing_id = lr.id
    join public.gerencias g on g.id = lg.gerencia_id
    where (
      (lg.interval_start_hour is null or lg.interval_end_hour is null)
      or (lg.interval_start_hour = lg.interval_end_hour)
      or (
        lg.interval_start_hour < lg.interval_end_hour
        and v_current_hour >= lg.interval_start_hour
        and v_current_hour < lg.interval_end_hour
      )
      or (
        lg.interval_start_hour > lg.interval_end_hour
        and (v_current_hour >= lg.interval_start_hour or v_current_hour < lg.interval_end_hour)
      )
    )
  ),
  phone_counts as (
    select
      c.*,
      count(gp.id)::integer as total_phone_count,
      count(gp.id) filter (
        where gp.status = 'active'
          and gp.assignment_role = 'acquisition'
      )::integer as active_phone_count
    from candidates c
    left join public.gerencia_phones gp
      on gp.gerencia_id = c.gerencia_id
     and gp.kind = c.phone_kind
    group by
      c.landing_id,
      c.user_id,
      c.landing_name,
      c.gerencia_id,
      c.phone_kind,
      c.gerencia_external_id,
      c.gerencia_label
  ),
  inserted as (
    insert into public.landing_phone_availability_demands (
      request_id,
      user_id,
      landing_id,
      landing_name,
      gerencia_id,
      gerencia_external_id,
      gerencia_label,
      phone_kind,
      had_active_phone,
      active_phone_count,
      total_phone_count,
      was_selected,
      selected_phone_id,
      selected_phone,
      result_status,
      source,
      checked_at
    )
    select
      p_request_id,
      pc.user_id,
      pc.landing_id,
      pc.landing_name,
      pc.gerencia_id,
      pc.gerencia_external_id,
      pc.gerencia_label,
      pc.phone_kind,
      pc.active_phone_count > 0,
      pc.active_phone_count,
      pc.total_phone_count,
      p_selected_gerencia_id is not null and pc.gerencia_id = p_selected_gerencia_id,
      case when p_selected_gerencia_id is not null and pc.gerencia_id = p_selected_gerencia_id then p_selected_phone_id else null end,
      case when p_selected_gerencia_id is not null and pc.gerencia_id = p_selected_gerencia_id then nullif(trim(coalesce(p_selected_phone, '')), '') else null end,
      coalesce(nullif(trim(p_result_status), ''), 'unknown'),
      coalesce(nullif(trim(p_source), ''), 'landing-phone'),
      now()
    from phone_counts pc
    on conflict (request_id, gerencia_id) do nothing
    returning 1
  )
  select count(*)::integer into v_inserted from inserted;

  return jsonb_build_object('ok', true, 'inserted', v_inserted);
end;
$$;

revoke all on function public.record_landing_phone_availability_demand(text, uuid, text, text, integer, bigint, text) from public;
grant execute on function public.record_landing_phone_availability_demand(text, uuid, text, text, integer, bigint, text) to service_role;

comment on function public.record_landing_phone_availability_demand(text, uuid, text, text, integer, bigint, text) is
  'Records demand-based availability for every candidate gerencia after landing-phone resolves a request.';

create or replace function public.get_gerencia_availability_summaries(
  p_user_id uuid default null,
  p_start timestamptz default null,
  p_end timestamptz default null
)
returns table (
  label text,
  sample_count integer,
  active_sample_count integer,
  availability_pct numeric
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_auth_uid uuid := auth.uid();
  v_is_admin boolean := false;
begin
  if v_auth_uid is null then
    raise exception 'not authorized';
  end if;

  if p_user_id is null or v_auth_uid <> p_user_id then
    select exists (
      select 1
      from public.profiles p
      where p.id = v_auth_uid
        and p.role = 'admin'
    )
    into v_is_admin;

    if not v_is_admin then
      raise exception 'not authorized';
    end if;
  end if;

  return query
  select
    d.gerencia_label as label,
    count(*)::integer as sample_count,
    count(*) filter (where d.had_active_phone)::integer as active_sample_count,
    case
      when count(*) > 0 then
        (count(*) filter (where d.had_active_phone)::numeric / count(*)::numeric) * 100
      else null
    end as availability_pct
  from public.landing_phone_availability_demands d
  where (p_user_id is null or d.user_id = p_user_id)
    and (p_start is null or d.checked_at >= p_start)
    and (p_end is null or d.checked_at <= p_end)
  group by d.gerencia_label
  order by 1 asc;
end;
$$;

grant execute on function public.get_gerencia_availability_summaries(uuid, timestamptz, timestamptz) to authenticated;

create or replace function public.cron_warm_landing_phone()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  base_url text;
  landing_url text;
  landing_name text;
begin
  select value into base_url from public.cron_config where key = 'sync_phones_url';
  if base_url is null or base_url like '%REPLACE_%' then
    return;
  end if;

  select name into landing_name from public.landings limit 1;
  landing_name := coalesce(nullif(trim(landing_name), ''), 'warmup');

  landing_url := replace(base_url, '/functions/v1/sync-phones', '/functions/v1/landing-phone')
    || '?name=' || landing_name
    || '&source=warmup';

  perform net.http_get(
    url := landing_url,
    headers := '{}'::jsonb,
    timeout_milliseconds := 15000
  );
end;
$$;

comment on function public.cron_warm_landing_phone() is
  'Invoca GET landing-phone para mantener la Edge Function caliente sin registrar demanda real.';
