-- Manual gerencias have one phone category. Keep existing landing assignments
-- aligned with the phones before enforcing the rule for future writes.
UPDATE public.gerencia_phones AS gp
SET kind = 'mkt'
FROM public.gerencias AS g
WHERE g.id = gp.gerencia_id
  AND g.source_type = 'manual'
  AND gp.kind IS DISTINCT FROM 'mkt';

UPDATE public.landings_gerencias AS lg
SET phone_kind = 'mkt'
FROM public.gerencias AS g
WHERE g.id = lg.gerencia_id
  AND g.source_type = 'manual'
  AND lg.phone_kind IS DISTINCT FROM 'mkt';

-- The landing-level default is displayed by older clients. Change it only
-- when every assigned gerencia is manual, leaving mixed landings untouched.
UPDATE public.landings AS l
SET phone_kind = 'mkt'
WHERE l.phone_kind IS DISTINCT FROM 'mkt'
  AND EXISTS (
    SELECT 1 FROM public.landings_gerencias AS lg
    JOIN public.gerencias AS g ON g.id = lg.gerencia_id
    WHERE lg.landing_id = l.id AND g.source_type = 'manual'
  )
  AND NOT EXISTS (
    SELECT 1 FROM public.landings_gerencias AS lg
    JOIN public.gerencias AS g ON g.id = lg.gerencia_id
    WHERE lg.landing_id = l.id AND g.source_type <> 'manual'
  );

-- Cached constructor responses can carry the former category. They will be
-- regenerated by the existing refresh job; no assignment counter is changed.
DELETE FROM public.landing_phone_cache AS cache
WHERE EXISTS (
  SELECT 1 FROM public.landings_gerencias AS lg
  JOIN public.gerencias AS g ON g.id = lg.gerencia_id
  WHERE lg.landing_id = cache.landing_id AND g.source_type = 'manual'
);

CREATE FUNCTION private.require_manual_phone_mkt()
RETURNS trigger
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = ''
AS $$
BEGIN
  IF NEW.kind IS DISTINCT FROM 'mkt'
     AND EXISTS (
       SELECT 1 FROM public.gerencias AS g
       WHERE g.id = NEW.gerencia_id AND g.source_type = 'manual'
     ) THEN
    RAISE EXCEPTION USING
      ERRCODE = '23514',
      MESSAGE = 'Los teléfonos de gerencias manuales deben ser de tipo mkt.';
  END IF;
  RETURN NEW;
END;
$$;
REVOKE ALL ON FUNCTION private.require_manual_phone_mkt() FROM PUBLIC, anon, authenticated;
CREATE TRIGGER require_manual_phone_mkt
BEFORE INSERT OR UPDATE OF gerencia_id, kind ON public.gerencia_phones
FOR EACH ROW EXECUTE FUNCTION private.require_manual_phone_mkt();

CREATE FUNCTION private.require_manual_assignment_mkt()
RETURNS trigger
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = ''
AS $$
BEGIN
  IF NEW.phone_kind IS DISTINCT FROM 'mkt'
     AND EXISTS (
       SELECT 1 FROM public.gerencias AS g
       WHERE g.id = NEW.gerencia_id AND g.source_type = 'manual'
     ) THEN
    RAISE EXCEPTION USING
      ERRCODE = '23514',
      MESSAGE = 'Las landings con gerencias manuales deben usar teléfonos mkt.';
  END IF;
  RETURN NEW;
END;
$$;
REVOKE ALL ON FUNCTION private.require_manual_assignment_mkt() FROM PUBLIC, anon, authenticated;
CREATE TRIGGER require_manual_assignment_mkt
BEFORE INSERT OR UPDATE OF gerencia_id, phone_kind ON public.landings_gerencias
FOR EACH ROW EXECUTE FUNCTION private.require_manual_assignment_mkt();

-- Converting a populated PBadmin gerencia to manual keeps its phones and
-- landing assignments consistent in the same transaction.
CREATE FUNCTION private.normalize_gerencia_switched_to_manual()
RETURNS trigger
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = ''
AS $$
BEGIN
  IF NEW.source_type = 'manual' AND OLD.source_type IS DISTINCT FROM 'manual' THEN
    UPDATE public.gerencia_phones AS gp
    SET kind = 'mkt'
    WHERE gp.gerencia_id = NEW.id AND gp.kind IS DISTINCT FROM 'mkt';

    UPDATE public.landings_gerencias AS lg
    SET phone_kind = 'mkt'
    WHERE lg.gerencia_id = NEW.id AND lg.phone_kind IS DISTINCT FROM 'mkt';

    UPDATE public.landings AS l
    SET phone_kind = 'mkt'
    WHERE l.phone_kind IS DISTINCT FROM 'mkt'
      AND EXISTS (
        SELECT 1 FROM public.landings_gerencias AS lg
        WHERE lg.landing_id = l.id AND lg.gerencia_id = NEW.id
      )
      AND NOT EXISTS (
        SELECT 1 FROM public.landings_gerencias AS lg
        JOIN public.gerencias AS g ON g.id = lg.gerencia_id
        WHERE lg.landing_id = l.id AND g.source_type <> 'manual'
      );
  END IF;
  RETURN NEW;
END;
$$;
REVOKE ALL ON FUNCTION private.normalize_gerencia_switched_to_manual() FROM PUBLIC, anon, authenticated;
CREATE TRIGGER normalize_gerencia_switched_to_manual
AFTER UPDATE OF source_type ON public.gerencias
FOR EACH ROW EXECUTE FUNCTION private.normalize_gerencia_switched_to_manual();
